### ISSUE TITLE
cannot add requests

### ISSUE THREAD

**Issue by joshpitzalis** [kenrogers/ninjatracker#2]
when I try and add a request it just raises an error alert with 'Status is required'.

**Comment by codeHatcher** [comment]
share your github repo so someone can help you

**Comment by joshpitzalis** [comment]
Ninja tracker has been updated to Add status to request insert method https://github.com/kenrogers/ninjatracker/commit/b2e46614707de107d30fa41931aa87f12bcbf674

Works now. 

Will share repo next time I raise an issue. Thanks @codeHatcher
